config_root_path: "config/"
model: {
    "model_name": "v6d2_f3_cb_d2est_split",
    "dummy_input_size_h": 720,
    "dummy_input_size_w": 1280,
    "history_encoders": {
        "num": 2,
    },
    "loss_config": {
        "zero_flow_mask": true,
        "zero_flow_ratio": 0.05,
    },
    loss: [
        "zero_flow",
    ],
    "feature_config": {
        "flow_residual_scale": 0.1,
        'rmv_fuse_id': 3,
        'st_rmv_fuse_id': 4,
    },
    "debug": [],
    "feature": [
        "flow_residual_scale",
        # "lmv_sigmoid",
        "demodulate",
        "demodulate_before_warp",
        # "demodulate_after_warp",
        "recurrent_d2e",
        "recurrent_d2e_decoding_split",
        # "recurrent_d2e_st",
        # "recurrent_d2d",
        # "recurrent_lmv",
        "feature_warp",
        "input_block",
        "output_block",
        "st",
        "single_encoding_split_st",
        # "st_encoder",
        "st_feature_warp",
        # "recurrent_lmv",
        # "st_residual",
        # "sky_residual",
        # "st_encoder",
        'rmv_fuse',
        'initial_by_rmv',
        'st_rmv_fuse',
        'st_initial_by_rmv',
        "tmv_skip_conn",
        # "st_lmv",
        # "st_lmv_cat",
        "st_lmv_res",
        "st_lmv_res_cat",
        # "his_st_lmv",
        "his_st_lmv_res",
        "his_st_lmv_res_cat",
        #=========================
        # "lmv",
        # "lmv_cat",
        "lmv_res",
        "lmv_res_cat",
        # "his_lmv",
        # "his_lmv_cat",
        "his_lmv_res",
        "his_lmv_res_cat",
        # "output_block_warp",
        # "output_block_st_warp",
        # "sky_st_warp",
    ],
}